using Dmart.Services;
using Shouldly;
using Xunit;

namespace Dmart.Tests.Unit.Services;

// Unit tests for the import work-list sidecar (`--save-list` / `--from-list`).
// Properties under test:
//   1. Write → Read round-trips the relative paths verbatim.
//   2. Read skips blank lines and `#` comments (so hand-edited / tool-generated
//      lists are tolerated).
//   3. Write is atomic (.tmp + rename) and overwrites an existing list.
//   4. Read on a missing file throws (the CLI must surface it, not silently
//      import nothing).
public sealed class ImportWorkListTests : IDisposable
{
    private readonly string _dir;

    public ImportWorkListTests()
    {
        _dir = Path.Combine(Path.GetTempPath(), $"worklist-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_dir);
    }

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch { }
    }

    [Fact]
    public void Write_Then_Read_RoundTrips()
    {
        var path = Path.Combine(_dir, "list.txt");
        var rels = new[]
        {
            "people/distributor/.dm/meta.folder.json",
            "people/.dm/curltest/meta.content.json",
            "a/b/c/.dm/x/attachments.media/meta.img.json",
        };

        ImportWorkList.Write(path, rels);
        var read = ImportWorkList.Read(path);

        read.ShouldBe(rels);
    }

    [Fact]
    public void Read_SkipsBlankLinesAndComments()
    {
        var path = Path.Combine(_dir, "list.txt");
        File.WriteAllText(path,
            "# generated by preflight\n" +
            "people/.dm/a/meta.content.json\n" +
            "\n" +
            "   \n" +
            "  people/.dm/b/meta.content.json  \n" +   // surrounding whitespace trimmed
            "# trailing comment\n");

        var read = ImportWorkList.Read(path);

        read.ShouldBe(new[]
        {
            "people/.dm/a/meta.content.json",
            "people/.dm/b/meta.content.json",
        });
    }

    [Fact]
    public void Write_IsAtomic_And_Overwrites()
    {
        var path = Path.Combine(_dir, "list.txt");
        ImportWorkList.Write(path, new[] { "old/.dm/x/meta.content.json" });
        ImportWorkList.Write(path, new[] { "new/.dm/y/meta.content.json", "new/.dm/z/meta.content.json" });

        // No leftover temp file, and the second write fully replaced the first.
        File.Exists(path + ".tmp").ShouldBeFalse();
        ImportWorkList.Read(path).ShouldBe(new[]
        {
            "new/.dm/y/meta.content.json",
            "new/.dm/z/meta.content.json",
        });
    }

    [Fact]
    public void Read_MissingFile_Throws()
    {
        var path = Path.Combine(_dir, "does-not-exist.txt");
        Should.Throw<IOException>(() => ImportWorkList.Read(path));
    }

    [Fact]
    public void DefaultPathFor_IsHiddenSidecar_InSource()
    {
        ImportWorkList.DefaultPathFor("/var/lib/dmart/galleon")
            .ShouldBe(Path.Combine("/var/lib/dmart/galleon", ".dmart-import-worklist.txt"));
    }
}
